# Generated by Django 4.0.2 on 2022-09-05 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('booking_date', models.DateField(default=django.utils.timezone.now, max_length=255)),
                ('booking_ToD', models.TimeField(default=django.utils.timezone.now, max_length=255)),
                ('number_of_guests', models.IntegerField()),
                ('phone_number', models.CharField(max_length=1024)),
                ('special_request', models.TextField(blank=True, max_length=1024)),
            ],
            options={
                'ordering': ['-last_name'],
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-email'],
            },
        ),
    ]
