# Generated by Django 4.0.2 on 2022-09-14 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0003_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_ToD',
            field=models.TimeField(blank=True, max_length=255, null=True),
        ),
    ]
